from compressionNN import compressed_nn
from compressionNN import pruning
from compressionNN import weightsharing
from compressionNN import pruning_weightsharing
from compressionNN import stochastic
from compressionNN import huffman
from compressionNN import sparse_huffman
from compressionNN import sparse_huffman_only_data
